DROP TABLE STAFF;
DROP TABLE DOCTOR_PERMISSIONS;
DROP TABLE STAFF_DOCTOR;
DROP TABLE HEALTH_STATE;
DROP TABLE PROCEDURES;
DROP TABLE ADDRESS;
DROP TABLE DOCTORS;
DROP TABLE PATIENTS;
DROP TABLE VISITATION_RECORDS;
DROP TABLE USERS;
DROP TABLE APPOINTMENTS;


